### ISSUE TITLE
SSL: SSLV3_ALERT_HANDSHAKE_FAILURE under mod_wsgi Apache

### ISSUE THREAD

**Issue by callefoss** [playingmedia/swish-python#5]
Working fine in a flask app but when put on an Apache server using mod_wsgi I get the SSLV3_ALERT_HANDSHAKE_FAILURE error. Understand it is nothing wrong with the framework itself, but if somebody has any idea of what the issue is under mod_wsgi could be?

Thx

**Comment by MadSpindel** [comment]
Try to upgrade your OpenSSL version.

**Comment by callefoss** [comment]
Thank but did not work. Upgraded to OpenSSL 1.0.2k. I am on OS X 10.11.6, Apache/2.4.18 and Python 2.7.13

Same problem.

**Comment by callefoss** [comment]
Got an indication that due to the fact that both OpenSSL and Python are installed using Homebrew and my Apache is not, my cause this problem.

**Comment by zrajna** [comment]
I'm on OpenSSL 1.1.1 (11 Sep 2018) and I still get this error (Python 3.6.9).
The following tests fail for me:

- `FAILED test_client.py::SwishClientTestCase::test_create_payment_ecommerce`
- `FAILED test_client.py::SwishClientTestCase::test_create_payment_error`
- `FAILED test_client.py::SwishClientTestCase::test_create_payment_mcommerce`
- `FAILED test_client.py::SwishClientTestCase::test_create_refund`
- `FAILED test_client.py::SwishClientTestCase::test_get_payment`
- `FAILED test_client.py::SwishClientTestCase::test_get_refund`

The exact error is:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='mss.cpc.getswish.net', port=443): Max retries exceeded with url: /swish-cpcapi/api/v1/paymentrequests (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:852)'),))`

I originally built the context manually (without swish-python) with the current cert, key and payeeAlias from mss_test_1.8.1 (and also the v2 put API), and eventually always get this error with Python.
The test API works like a charm with CURL though from the same machine...
